apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-from-scratch
spec:
  source:
    helm:
      releaseName: application-from-helm
    path: nginx
    repoURL: 'https://github.com/gabe-certs/argocdtst.git'
    targetRevision: main
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
